[package]
name = "evobase-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = ["legacy"]
legacy = ["dep:evobase-core", "dep:uuid"]

[dependencies]
evobase-appspec = { path = "../evobase-appspec" }
evobase-core = { path = "../evobase-core", optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true, optional = true }
