[package]
name = "evobase-messaging"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

evobase-core = { path = "../evobase-core" }

[dev-dependencies]
serde_json.workspace = true
