from pathlib import Path
import json,zipfile,hashlib,re,math
from PIL import Image,ImageDraw,ImageFont
ROOT=Path(__file__).resolve().parent;S=json.loads((ROOT/'source/screens.json').read_text());OUT=ROOT/'packages';OUT.mkdir(exist_ok=True)
PACKS=[
('01-foundation','Foundation / M3 Expressive shells',['workspace','new-app','settings','states','components'],['010-contracts-and-bootstrap.md'],'workspace', 'Thống nhất AppSpec/host boundaries, source tokens, adaptive shells và trạng thái phiên. Provider sign-in journey chờ identity ADR.', ['Token source→generated output→mounted consumer trace; không fork palette','Workspace/Builder/Runtime navigation separate; compact Builder read-only summary','Light/dark, focus, VI/EN, reduced motion, zoom/text-scale evidence','Denied/session-expired giữ unsent draft; không coi settings là auth journey hoàn chỉnh']),
('02-data-grid','Typed data / grid / import',['builder-data','field-inspector','import-resolve'],['020-appspec-kernel.md','030-typed-grid-and-import.md'],'builder-data','Kernel semantics trước grid. Bảng có kiểu và Ref hiển thị nhãn, lưu identity; import cần resolve.', ['Golden codec/ID/type/Ref round-trip vectors độc lập GUI/SQL','Ref wrong table/missing/ambiguous/cross-scope bị chặn; reverse derived','Grid keyboard/IME/paste/sort/rename không selection drift; currency unit rõ','Cần hiện receipt/revision và lỗi theo ô, không giả save success']),
('03-structure-formulas','Relations / formulas',['relations','formula'],['040-relations-and-formulas.md'],'relations','Quan hệ và biểu thức thuần cùng stable-ID binding; captured price khác live lookup.', ['Baseline N:1 + restrict có conformance; 1:1/N:M disabled đến khi test/gate đạt','Không hai canonical directions; edges/indexes projection có consistency proof','Formula type/resource bounds; computed output policy, không partial visible-child total giả','Rename/reorder/label đổi vẫn giữ nghĩa; targeted differential/golden tests']),
('04-policies-commands','Authority / policy / commands',['policy','command'],['050-authority-policies-commands.md'],'policy','Câu cấu trúc dễ hiểu với current authority, guards và typed receipt.', ['Host boundary AND current grants AND app policy AND restrictions; missing context deny','Relation/picker/join/export/aggregate không ngầm mở quyền','Old+new state và field mutability kiểm tại command commit','Request key binds immutable intent; exact retry returns original receipt under current grants; no effect duplication']),
('05-hosted-isolation','Isolated fixed-store spike',['tenant-ops'],['060-isolated-fixed-store.md'],'tenant-ops','Đo fixed-layout engine store và database-per-tenant, giữ lựa chọn ADR chưa settled production.', ['Hai tenant DB + provisioner/runtime role separation; runtime no DDL/BYPASSRLS','Thêm logical table/optional field/Ref/publish không business SQL DDL; actual catalog evidence','Records/edges/index/unique/revision/outbox atomic; concurrency/restart/failure vectors','Tenant negative tests gồm API/Ref/cache/subscription/blob/log/bot; resource/latency measurements + support envelope ADR']),
('06-release','Preview / release / evolution',['view-builder','preview','publish','migration'],['070-release-and-preview.md','080-schema-evolution.md'],'publish','Preview zero delivery, immutable checked release, impact/backfill/recovery trước activation.', ['Draft edits never activate; preview no live writes/no external dispatch','AppSpec/model/data/binding/policy revisions separate; app instance pins release','Type/required/backfill impact preview + atomic cutover/recovery proof; no-DDL still migration','Live runs keep pinned version; rollback/restore does not unsend/replay effects or revive revoked grants']),
('07-runtime','Runtime web / CMP',['runtime-home','runtime-detail','runtime-form','approval'],['090-runtime-web-cmp.md'],'runtime-home','List-detail/form/approval có phép; mobile ưu tiên việc thực cần làm, không modeling trên phone.', ['Only authorized projection/actions render; trusted runtime still enforces','Save draft vs Submit distinct; receipt/revision/conflict/no-false-sent semantics','Approval old+new/current grants and reviewed revision; reject explicit; Close/Back not decision','Visible navigation-up, Android Back/iOS edge/browser history/IME/safe-area + native CMP evidence separate from mobile Web']),
('08-functions','Durable declarative functions',['functions','run-detail'],['100-durable-functions.md'],'functions','Finite typed steps, durable waits và trạng thái gửi chưa rõ kết quả.', ['Pinned plan/run IDs/input snapshot/checkpoint/lease fencing and per-tenant budgets','Transaction + event/outbox atomic; no network wait while holding DB transaction','Lost ACK/duplicate/timer/restart/late-worker tests; bounded transient retries/permanent quarantine','OutcomeUnknown + reconcile/correlation; current consent at dispatch; no exactly-once external promise']),
('09-connectors','Email / webhook capability bindings',['connectors'],['110-connectors.md'],'connectors','Contract capabilities thực, host account/consent/secret handles riêng definition.', ['Email fake provider labeled simulated; real-target evidence only after authorized test','Verified webhook/dedup/tenant correlation; payload cannot grant actor or tenant','Secret handles/accounts chỉ ở host bindings; portable definition chỉ abstract connector contracts, không host-secret binding; egress/consent recheck','Zalo separate adapter spike/permissions; unsupported disabled; phone number not automatic valid recipient']),
('10-messaging','Business inbox / messaging',['inbox'],['120-messaging.md'],'inbox','Hộp thư có context với protected transport metadata.', ['Conversation/message/participant/delivery typed managed projections','Provider IDs/receipts read-only; generic edit cannot fake delivered/received','Scoped inbox/attachment/search + current output policy tests','Draft message separate dispatch; unknown delivery clearly shown; no federation/E2EE requirement for MVP']),
('11-scoped-bot','Scoped service-actor bot',['bot-scope'],['130-scoped-bot.md'],'bot-scope','Allowed projections/commands, budgets, consent và human approval.', ['Verified identity linking; display name not authority','Retrieved content untrusted; no permission elevation/tool instruction from messages','Bot cannot MarkPaid/change inventory/policy/credentials without app policy and authorized command','Index/search/cache/history tenant+current-grant scope, prompt injection/denied/no-model-binding tests']),
('12-portability','Local profile / recovery',['offline'],['140-portability-recovery.md'],'offline','ADR support envelope cho portable execution, local unsent draft và restore.', ['Bounded codec/version/provenance and stable identity compatibility, .evobase extension ADR','Local snapshot does not grant hosted authority; no falsely confirmed offline send','Conflict needs review; reauth/revalidation/current permissions at sync','Restore/export/receipts test: no revoked-grant resurrection or arbitrary external replay'])
]
items=[];md=['# Screen map and flows','', 'Target design only. 27 authored screens; each has desktop and compact static frames. Compact Builder is read-only summary; compact Runtime is intended native CMP target, not native evidence.','', '## Primary journey','', 'Workspace → Create draft → Typed grid / fields / import resolve → Relations / formula → Policy / command → Preview → Release review / evolution → Authorized Runtime → Form / approval → Function run / connector / inbox.','', 'Provider sign-in is deferred to identity ADR; denied and expired-session states are covered. General1:1/N:M and offline/provider capabilities remain gated.','']
for slug,title,ids,prompts,rep,scope,gates in PACKS:
 sc=[s for s in S if s['id'] in ids];md += [f'## {slug} · {title}', '',scope,'']
 for s in sc:md += [f'### {s["id"]} · {s["title"]}',f'- Surface: {s["surface"]}; primary intent: {s["action"]}',f'- Flow: {s["section"]}; inspect/cancel/back preserve draft; no live effects in fixture',f'- Required states: loading / empty / denied / invalid / pending / confirmed / conflict / unsupported as applicable',f'- Developer invariant: {s["note"]}',f'- Editable frame: frames/{s["id"]}-desktop.svg; compact: frames/{s["id"]}-mobile.svg','']
 for g in gates:md += ['- Acceptance: '+g]
 md += ['']
 # One bounded ZIP; scoped screen data, editable frames, only relevant previews and shared adapters.
 z=OUT/f'evobase-{slug}.zip'
 with zipfile.ZipFile(z,'w',zipfile.ZIP_DEFLATED,compresslevel=9) as a:
  files=[ROOT/'build.py',ROOT/'render_static.py',ROOT/'source/index.html',ROOT/'source/style.css',ROOT/'source/app.mjs',ROOT/'source/tokens.json',ROOT/'source/tokens.css',ROOT/'assets/evobase-mark.svg',ROOT/'assets/relation-orbit.svg',ROOT/'assets/OpenSans-Regular.ttf',ROOT/'assets/OpenSans-Semibold.ttf',ROOT/'assets/OpenSans-NOTICE.txt',ROOT/'assets/LICENSE-Apache-2.0.txt',ROOT/'specs/component-contract.md',ROOT/'specs/accessibility-and-states.md',ROOT/'specs/source-to-design.md']
  for p in files:a.write(p,p.relative_to(ROOT))
  a.writestr('source/screens.json',json.dumps(sc,ensure_ascii=False,indent=2));a.writestr('source/data.mjs','export const screens = '+json.dumps(sc,ensure_ascii=False,indent=2)+';\n')
  for id in ids:
   for variant in ['desktop','mobile']:
    for folder,ext in [('frames','svg'),('previews','png')]:p=ROOT/folder/f'{id}-{variant}.{ext}';a.write(p,p.relative_to(ROOT))
  for p in (ROOT/'previews').glob('*-dark.png'):
   if p.name.split('-desktop')[0].split('-mobile')[0] in ids:a.write(p,p.relative_to(ROOT));q=ROOT/'frames'/p.with_suffix('.svg').name;a.write(q,q.relative_to(ROOT))
  summary='# '+title+'\n\nDesign/planning only; no implementation or provider evidence.\n\n'+scope+'\n\n## Screens\n'+'\n'.join('- '+id for id in ids)+'\n\n## Sequential prompts\n'+'\n'.join('- docs/work-plan/'+p for p in prompts)+'\n\n## Acceptance\n'+'\n'.join('- [ ] '+g for g in gates)+'\n\n## Deferred\nNo default switch, merge, deploy, live migration, arbitrary provider delivery or legacy retirement.\n'
  entry=summary+'\n## Entry points in this scoped ZIP\n- source/index.html: scoped fixture prototype (use an approved static server; no external calls). The first included screen is the default. Links to absent screens explain the separate pack.\n- source/tokens.json + tokens.css + style.css + app.mjs: editable canonical theme/components.\n- frames/: editable SVG for these screens only.\n- previews/: matching static PNGs; not browser/native screenshots.\n- specs/component-contract.md, specs/accessibility-and-states.md and specs/source-to-design.md: shared contracts and evidence limits.\n- build.py regenerates local token CSS/fixture data/contact sheets from the scoped source; render_static.py rerenders using a portable ROOT-derived font config.\n- assets/: original vector assets, bundled Apache-2.0 fonts/license/notice.\n\nOther packs, global contact sheets and the global issue index are available on the dedicated design branch, not included here.\n'
  a.writestr('PACK.md',summary);a.writestr('README.md',entry)
 items.append({'pack':slug,'title':title,'screens':ids,'prompts':prompts,'representative':rep,'scope':scope,'gates':gates,'zip':'packages/'+z.name,'zip_bytes':z.stat().st_size,'sha256':hashlib.sha256(z.read_bytes()).hexdigest()})
(ROOT/'specs/screen-map.md').write_text('\n'.join(md)+'\n')
(OUT/'pack-index.json').write_text(json.dumps({'version':1,'evidence':'static-svg-raster + fixture-prototype; no live app proof','screen_count':len(S),'packs':items},ensure_ascii=False,indent=2)+'\n')
print(json.dumps([{'pack':x['pack'],'bytes':x['zip_bytes'],'screens':len(x['screens'])} for x in items],ensure_ascii=False))
